{{- if not (empty $.Values.service2) }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.appName }}-2
  labels:
    app: {{ $.Values.appName }}-2
spec:
  type: {{ .Values.service2.type }}
  ports:
    - port: {{ .Values.service2.port }}
      targetPort: {{ .Values.service2.targetPort }}
      protocol:  {{ .Values.service2.protocol }}
      name: http
  selector:
    app: {{ $.Values.appName }}

{{- end }}

